controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index_page:
    path: /
    controller: App\Controller\IndexController::index

get_ticker:
    path: /ticker
    controller: App\Controller\TickerController::getTickerData

