<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDAesfEv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDAesfEv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDAesfEv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDAesfEv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDAesfEv\App_KernelDevDebugContainer([
    'container.build_hash' => 'DAesfEv',
    'container.build_id' => '9f1ce8b1',
    'container.build_time' => 1676063832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDAesfEv');
